v2.2.3

diff --git a/zen_notify b/zen_notify
--- a/zen_notify
+++ b/zen_notify
@@ -24,7 +24,8 @@ nvdir=/usr/local/zenvidia
 script_conf=$nvdir/script.conf
 basic_conf=$local_nvdir/basic.conf
 nvtmp=$local_nvdir/notify
-deficon=swiss_knife
+# deficon=swiss_knife
+deficon=zen-emblem
 ## check if zen_taskbar_menu exit
 zen_bar=$(command -v zen_task_menu)
 [ $script_conf ] || exit 0
@@ -33,7 +34,7 @@ zen_bar=$(command -v zen_task_menu)
 ## script could need to sleep during the desktop session boot time.
 ## to uncomment only in case of session autostart notif issue.
 # sleep 15
-ifs=$IFS
+
 
 [ -d $nvtmp ] || mkdir -p $nvtmp
 ARCH=$HOSTTYPE
@@ -46,164 +47,178 @@ local_src=$local_nvdir/src
 ## reset all notif display options
 driver_up=0
 zen_up=0
-
+msg_suffix='update'
+ping -c2 www.nvidia.com &>/dev/null
+cnx=$?
+ifs=$IFS
+## capture for exit status
+trap "IFS=\$ifs rm -f $drv_temp" EXIT
 driver_ctrl(){
-	## default driver caracters max count.
-	nb=9
-	## get all driver list.
-	wget -q -O $drv_temp https://$nvidia_ftp-$ARCH/
-	## get latest.txt file.
-	wget -q -O $last_update https://$nvidia_ftp-$ARCH/latest.txt
-	## latest.txt fiel dfine current official version.
-	## end of all driver list define the beta version if different from diiferent of official.
-	cat $drv_temp| sed -En "s/^.*href.*'(.*)\/'>.*$/\1/p" > $drv_list
-	cat $drv_temp| sed -En "s/^.*href.*'(.*)\/'>.*$/\1/p"| tail -n1 > $last_beta
-	LAST_DRV=$(cat $last_update | awk '{ print $1 }')
-	LAST_BETA=$(cat $last_beta)
-
-	## driver version could be in the form xxx.xxx.xxx or xxx.xx
-	## it is needed to short it to number only.
-	offi_short=$(echo "$LAST_DRV"| sed -n "s|\.||g;p")
-	beta_short=$(printf "$LAST_BETA"| sed -n "s|\.||g;p")
-
-	if [ -s $nvdir/version.txt ]; then
-		version=$(cat $nvdir/version.txt)
-	else
-		version=$(modinfo -F version nvidia)
-	fi
+	## reset all value.
 	unset ver_array last_array DRV_LIST
-	ver_array=( $(sed -n "s/\./ /g;p" <<< $version) )
-
-	if [ $beta_short -ne $offi_short ]; then
-		rem_diff=1
-		last_array=( $(sed -n "s/\./ /g;p" <<< $LAST_BETA) )
-	else
-		rem_diff=0
-		last_array=( $(sed -n "s/\./ /g;p" <<< $LAST_DRV) )
-	fi
-
 	drv_diff=0
 	greater=0
-	for ((i=0;i<=2;i++)) {
-			[ ${last_array[$i]} -eq ${ver_array[$i]} ] || drv_diff=1
-			[ ${last_array[$i]} -gt ${ver_array[$i]} ] && greater=1
-	}
-	if [ $rem_diff -eq 1 ]; then
-		DRV_LIST=( "$LAST_DRV, official driver" "$LAST_BETA, beta driver" )
-	else
-		DRV_LIST=( "$LAST_DRV, official drivers" )
-	fi
-	if [ ${#DRV_LIST[@]} -gt 0 ]; then
-		IFS=$(echo -en "\n\b")
-		cnt=0
-		for drv_line in ${DRV_LIST[@]}; do
-			driver=$(printf "$drv_line"|cut -d',' -f1)
-			release=$(printf "$drv_line"|cut -d',' -f2)
-			if [ $drv_diff -gt 0 ]; then
-				if [ $cnt -eq 0 ]; then sol='';eol=''; else sol='\n';eol=''; fi
-				if [[ $(grep -E -c "$driver" $drv_list) -gt 0 ]]; then
-					_driver_notif+=( "$sol<b>$driver</b> $release update.$eol" )
-				else
-					_driver_notif+=( "$sol<b>$driver</b> $release update.\n<i>(not dowloadable yet)</i>$eol" )
-				fi
-				((cnt++))
-			fi
-		done
-		if [[ $greater -gt 0 || ! $(echo -e "${DRV_LIST[*]}") =~ $(modinfo -F version nvidia) ]]; then
-			notif_msg+='Nvidia driver '
-			driver_up=1
+	rem_diff=0
+	if [ $cnx -eq 0 ]; then
+		## default driver caracters max count.
+		nb=9
+		## get all driver list.
+		wget -q -O $drv_temp https://$nvidia_ftp-$ARCH/
+		## get latest.txt file.
+		wget -q -O $last_update https://$nvidia_ftp-$ARCH/latest.txt
+		## latest.txt fiel dfine current official version.
+		## end of all driver list define the beta version if different from diiferent of official.
+		cat $drv_temp| sed -En "s/^.*href.*'(.*)\/'>.*$/\1/p" > $drv_list
+		cat $drv_temp| sed -En "s/^.*href.*'(.*)\/'>.*$/\1/p"| tail -n1 > $last_beta
+		LAST_DRV=$(cat $last_update | awk '{ print $1 }')
+		LAST_BETA=$(cat $last_beta)
+
+		## driver version could be in the form xxx.xxx.xxx or xxx.xx
+		## it is needed to short it to number only.
+		offi_short=$(echo "$LAST_DRV"| sed -n "s|\.||g;p")
+		beta_short=$(printf "$LAST_BETA"| sed -n "s|\.||g;p")
+
+		if [ -s $nvdir/version.txt ]; then
+			version=$(cat $nvdir/version.txt)
+		else
+			version=$(modinfo -F version nvidia)
 		fi
-		IFS=$ifs
+	# 	unset ver_array last_array DRV_LIST
+		ver_array=( $(sed -n "s/\./ /g;p" <<< $version) )
+
+		if [ $beta_short -ne $offi_short ]; then
+			rem_diff=1
+			last_array=( $(sed -n "s/\./ /g;p" <<< $LAST_BETA) )
+		else
+			rem_diff=0
+			last_array=( $(sed -n "s/\./ /g;p" <<< $LAST_DRV) )
+		fi
+		for ((i=0;i<=2;i++)) {
+				[ ${last_array[$i]} -eq ${ver_array[$i]} ] || drv_diff=1
+				[ ${last_array[$i]} -gt ${ver_array[$i]} ] && greater=1
+		}
+		if [ $rem_diff -eq 1 ]; then
+			DRV_LIST=( "$LAST_DRV, official driver" "$LAST_BETA, beta driver" )
+		else
+			DRV_LIST=( "$LAST_DRV, official drivers" )
+		fi
+		if [ ${#DRV_LIST[@]} -gt 0 ]; then
+			IFS=$(echo -en "\n\b")
+			cnt=0
+			for drv_line in ${DRV_LIST[@]}; do
+				driver=$(printf "$drv_line"|cut -d',' -f1)
+				release=$(printf "$drv_line"|cut -d',' -f2)
+				if [ $drv_diff -gt 0 ]; then
+					if [ $cnt -eq 0 ]; then sol='';eol=''; else sol='\n';eol=''; fi
+					if [[ $(grep -E -c "$driver" $drv_list) -gt 0 ]]; then
+						_driver_notif+=( "$sol<b>$driver</b> $release update.$eol" )
+					else
+						_driver_notif+=( "$sol<b>$driver</b> $release update.\n<i>(not dowloadable yet)</i>$eol" )
+					fi
+					((cnt++))
+				fi
+			done
+			if [[ $greater -gt 0 || ! $(echo -e "${DRV_LIST[*]}") =~ $(modinfo -F version nvidia) ]]; then
+				notif_msg+='Nvidia driver '
+				driver_up=1
+			fi
+		fi
+	fi
+	if [ $cnx -gt 0 ]; then
+		unset _driver_notif
+		notif_msg='Nvidia driver notification'
+		_driver_notif+='<b>WARNING</b> : No Signal'
+		msg_suffix=''
 	fi
 }
 source_ctrl(){
-	rep_git_local=$(find -P $HOME -maxdepth 4 -name "zenvidia" -type d)
-	if [ -d $rep_git_local ]; then
-		if [ $driver_up -gt 0 ]; then
-		notif_txt='and Zenvidia'; line='\n'
-		else
-		notif_txt='Zenvidia'; line=''
-		fi
-	#  	rep_git_local=$(find -P $HOME -maxdepth 4 -name "zenvidia" -type d)
-		tmp_git_src=$(mktemp -d --tmpdir tmp_git.XXX)
-		test -f $local_src/zen_git.log || touch $local_src/zen_git.log
-		IFS=$(echo -en "\n\b")
-		CHECK_GIT_REPO(){
-			local_date=$(env LANG=En_en date +%Y''%m''%d)
-			# extract date from log
-			git_rm_fetch_date=$(git log origin -n 1 | sed -n '/Date/p'| awk '{print $3" "$4" "$6}')
-			# convert date to comparable number
-			git_rm_date=$(date -d "$git_rm_fetch_date" +%Y''%m''%d)
-			# extract version line
-			git_rm_version=$(git log origin -n 1 | grep -E -o "v[0-9].*")
-			git_local_version=$(cat $local_nvdir/zen_version)
-			git_rm_fetch_log=$(git log origin -n 1 | sed -n "/-/,/-/p")
-			# before acting, we need to know the last pull record in local dir.
-			if [ $rep_git_local ]; then
-				pushd $rep_git_local
-				git_local_pull_date=$(cat .git/logs/refs/heads/master| grep "clone\|pull"|awk '{print $5}'|sed -n '$p')
-				git_pull_date=$(date -d "@$git_local_pull_date" +%Y''%m''%d)
-				if [ ! "$git_local_version" ]; then
-					git_local_version=$(git log origin -n 1 | grep -E -o "v[0-9].*")
-					test "$git_local_version" || git_local_version=0
-					echo -e "$git_local_version" > $local_nvdir/zen_version
-				fi
-				popd
+	if [ $cnx -eq 0 ]; then
+		rep_git_local=$(find -P $HOME -maxdepth 4 -name "zenvidia" -type d)
+		if [ -d $rep_git_local ]; then
+			if [ $driver_up -gt 0 ]; then
+			notif_txt='and Zenvidia'; line='\n'
 			else
-				git_pull_date=0
-				git_local_version=0
+			notif_txt='Zenvidia'; line=''
 			fi
-			# then, we need to know if log is about version update or issue warning message.
-			# log and issue is mandatory formated with a '-' in commit message.
-			if [ ${#git_rm_fetch_log[*]} -gt 0 ]; then
-				if [ "$git_rm_version" ]&&[ "$git_rm_version" != "$git_local_version" ]; then
-					if [ $(grep -c "$git_rm_fetch_date" $local_src/zen_git.log) -eq 0 ]; then
-						if [ $(grep -c "-" <<< ${git_rm_fetch_log[*]}) -gt 0 ]; then
-							cat <<-LOG >> $local_src/zen_git.log
-								$git_rm_fetch_date : $git_rm_version
-								$git_rm_fetch_log
-							LOG
+			# 	rep_git_local=$(find -P $HOME -maxdepth 4 -name "zenvidia" -type d)
+			tmp_git_src=$(mktemp -d --tmpdir tmp_git.XXX)
+			test -f $local_src/zen_git.log || touch $local_src/zen_git.log
+			IFS=$(echo -en "\n\b")
+			CHECK_GIT_REPO(){
+				local_date=$(env LANG=En_en date +%Y''%m''%d)
+				# extract date from log
+				git_rm_fetch_date=$(git log origin -n 1 | sed -n '/Date/p'| awk '{print $3" "$4" "$6}')
+				# convert date to comparable number
+				git_rm_date=$(date -d "$git_rm_fetch_date" +%Y''%m''%d)
+				# extract version line
+				git_rm_version=$(git log origin -n 1 | grep -E -o "v[0-9].*")
+				git_local_version=$(cat $local_nvdir/zen_version)
+				git_rm_fetch_log=$(git log origin -n 1 | sed -n "/-/,/-/p")
+				# before acting, we need to know the last pull record in local dir.
+				if [ $rep_git_local ]; then
+					pushd $rep_git_local
+					git_local_pull_date=$(cat .git/logs/refs/heads/master| grep "clone\|pull"|awk '{print $5}'|sed -n '$p')
+					git_pull_date=$(date -d "@$git_local_pull_date" +%Y''%m''%d)
+					if [ ! "$git_local_version" ]; then
+						git_local_version=$(git log origin -n 1 | grep -E -o "v[0-9].*")
+						test "$git_local_version" || git_local_version=0
+						echo -e "$git_local_version" > $local_nvdir/zen_version
+					fi
+					popd
+				else
+					git_pull_date=0
+					git_local_version=0
+				fi
+				# then, we need to know if log is about version update or issue warning message.
+				# log and issue is mandatory formated with a '-' in commit message.
+				if [ ${#git_rm_fetch_log[*]} -gt 0 ]; then
+					if [ "$git_rm_version" ]&&[ "$git_rm_version" != "$git_local_version" ]; then
+						if [ $(grep -c "$git_rm_fetch_date" $local_src/zen_git.log) -eq 0 ]; then
+							if [ $(grep -c "-" <<< ${git_rm_fetch_log[*]}) -gt 0 ]; then
+								cat <<-LOG >> $local_src/zen_git.log
+									$git_rm_fetch_date : $git_rm_version
+									$git_rm_fetch_log
+								LOG
+							fi
+						fi
+						issue=0
+					else
+						if [ $(grep -c "issue" <<< ${git_rm_fetch_log[*]}) -gt 0 ]; then
+							issue=1
+							git_rm_warn_log=$(cut -d'-' -f2 <<< ${git_rm_fetch_log[*]})
 						fi
 					fi
-					issue=0
-				else
-					if [ $(grep -c "issue" <<< ${git_rm_fetch_log[*]}) -gt 0 ]; then
-						issue=1
-						git_rm_warn_log=$(cut -d'-' -f2 <<< ${git_rm_fetch_log[*]})
-					fi
 				fi
-			fi
-				# if last pull/clone date is lower than the remote's, display update message.
-				if [ $git_pull_date -lt $git_rm_date ]; then
-					zen_up=1
-					# is the log message an issue warning ?
-					if [ $issue = 0 ]; then
-						notif_msg+="$notif_txt "
-						_driver_notif+=("${line}zenvidia git repo update.\n$git_rm_fetch_date $git_rm_version")
-					else
-						notif_msg+="$notif_txt "
-						_driver_notif+=("${line}zenvidia git warning.\n$git_rm_fetch_date $git_rm_warn_log")
+					# if last pull/clone date is lower than the remote's, display update message.
+					if [ $git_pull_date -lt $git_rm_date ]; then
+						zen_up=1
+						# is the log message an issue warning ?
+						if [ $issue = 0 ]; then
+							notif_msg+="$notif_txt "
+							_driver_notif+=("${line}zenvidia git repo update.\n$git_rm_fetch_date $git_rm_version")
+						else
+							notif_msg+="$notif_txt "
+							_driver_notif+=("${line}zenvidia git warning.\n$git_rm_fetch_date $git_rm_warn_log")
+						fi
 					fi
-				fi
-		}
-		# clone remote .git dir only to get changes.
-		pushd $tmp_git_src
-		git clone -n --depth=1 $zenvidia_git .
-		# then check diff in date, then in data, if local repos exist.
-		CHECK_GIT_REPO
-		popd
-		IFS=$ifs
-	else
-		zen_up=0
+			}
+			# clone remote .git dir only to get changes.
+			pushd $tmp_git_src
+			git clone -n --depth=1 $zenvidia_git .
+			# then check diff in date, then in data, if local repos exist.
+			CHECK_GIT_REPO
+			popd
+		else
+			zen_up=0
+		fi
 	fi
 }
 notifying(){
 	# only display notif if driver_ctrl or source_ctrl are true.
 	test -f $local_nvdir/taskbar_message || touch $local_nvdir/taskbar_message
 	echo -e "notif=0" > $local_nvdir/taskbar_message
-	if [[ $driver_up -gt 0 || $zen_up -gt 0 ]]; then
-
-		notify-send -t 5000 -u low -i $icon_set "${notif_msg[*]}update" "$(echo "${_driver_notif[@]}")"
+	if [[ $cnx -gt 0 || $driver_up -gt 0 || $zen_up -gt 0 ]]; then
+		notify-send -t 5000 -u low -i "$deficon" "${notif_msg[*]}$msg_suffix" "$(echo "${_driver_notif[@]}")"
 		echo -e "notif=1" > $local_nvdir/taskbar_message
 		echo -e "notif_text=\"${_driver_notif[@]}\"" >> $local_nvdir/taskbar_message
 	fi
@@ -218,19 +233,14 @@ usage_help(){
 	printf "\t -n : check nvidia only.\n"
 	printf "\t -h : this help.\n"
 }
-icon_set=$deficon
+# icon_set=$deficon
 test $# -gt 0 || usage_help
 while [ $# -gt 0 ]
 	getopts "z n h" OPT; do
 	case $OPT in
-		z)
-		driver_ctrl
-		source_ctrl
-		notifying
+		z) driver_ctrl; source_ctrl; notifying
 		;;
-		n)
-		driver_ctrl
-		notifying
+		n) driver_ctrl; notifying
 		;;
 		h) usage_help ;;
 	esac
